# --- Site Settings ---
title: "Sihi Lab"
description: "Soil and Environmental Systems Research at Emory University"
baseurl: "/Sihi-Lab-Website" # Your repository name
url: "https://Atharva-Pansare.github.io" # Your GitHub Pages URL

# --- Theme ---
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # You can try "air", "aqua", "contrast", etc.

# --- Navigation ---
# This creates the main navigation bar at the top
main_nav:
  - title: "Home"
    url: /
  - title: "People"
    url: /people/
  - title: "Teaching"
    url: /teaching/
  - title: "Publications"
    url: /publications/
  - title: "News"
    url: /news/

# --- Footer Links ---
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DebjaniSihiLab"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:debjani.sihi@emory.edu"
