# --- Site Settings ---
title: Sihi Lab | Soil and Environmental Systems Research
description: Research group of Dr. Debjani Sihi at NC State University.

# --- Build Settings ---
baseurl: "/Sihi-Lab-Website" 
url: "https://Atharva-Pansare.github.io" 

# --- Theme Settings ---
theme: jekyll-theme-cayman

# --- Plugins ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# --- NEW: Define Collections ---
# This tells Jekyll to look for a _people folder
# and to create individual pages for each person (output: true)
collections:
  people:
    output: true

# --- NEW: Set Defaults ---
# This automatically applies our custom layout to all pages
# and all "people" files, so we don't have to.
defaults:
  - scope:
      path: "" # an empty string for all files
    values:
      layout: "custom" # Use our new custom layout
