# --- Site Settings ---
# (Edit these to your liking)
title: Sihi Biogeochemistry Lab
description: Research group of Dr. Debjani Sihi at NC State University.

# --- Build Settings ---
# (These values are critical and now match YOUR account)
baseurl: "/Sihi-Lab-Website"  # This MUST match your repository name
url: "https://Atharva-Pansare.github.io" # This is YOUR personal GitHub Pages URL

# --- Theme Settings ---
theme: jekyll-theme-cayman

# --- Plugins ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag
